# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16nL381Vk8yQlCe3z0qBa9ZOugZ1jXyrs
"""

num = 21
 
 
if num > 1: 
 
      
    for i in range(2, num): 
 
          if (num % i) == 0: 
 
           print(num, "is not a prime number") 
 
           break
 
    else: 
 
        print(num, "is a prime number") 
 
else: 
 
   print(num, "is not a prime number")