# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xb5dOqocPlgKtZXrYgY-lgfc98-reN1a
"""

def maximum(a, b, c): 
 
    list = [a, b, c] 
 
    return max(list)
  
 
a = 100
 
b = 175
 
c = 160
 
print(maximum(a, b, c))