# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1csFP35GQ3OR_wBo5kCp_tPZ6xxVr6OAi
"""

txt = "Anil Kumar"[::-1]
print(txt)