# -*- coding: utf-8 -*-
"""Copy of Untitled37.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DIspAwe0iKrqOMrPTsnMoG2AordtTueM
"""

def Squaresum(n) : 
 
    return (n * (n+1) * (2 * n + 1)) // 6
 
n = 6
 
print(Squaresum(n))